spring:
  application:
    name: test-app
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085
        project-id: local
    stream:
      gcp:
        pubsub:
          default:
            consumer:
              ack-mode: AUTO_ACK
              auto-create-resources: true
            producer:
              auto-create-resources: true
      bindings:
        onArrival-in-0:
          destination: test-topic
          group: ${spring.application.name}
        sendTest-out-0:
          destination: test-topic
      output-bindings: sendTest
    function:
      definition: onArrival
  integration:
    management:
      observation-patterns: "*"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.google.cloud.spring.core: ERROR
    org.springframework.integration: DEBUG
